Repository Student-Center/3days-server, pull requests merged in 2024-09, with the labels that each got.

#3 [WEAV-24] ✨ 유저 도메인 생성 메서드 구현 및 테스트
  build.gradle.kts
  domain/src/main/kotlin/com/threedays/domain/user/entity/User.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/Gender.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/UserId.kt
  domain/src/test/kotlin/com/threedays/domain/user/entity/UserTest.kt
  gradle/libs.versions.toml
  support/common/src/main/kotlin/com/threedays/support/common/base/domain/UUIDTypeId.kt
Labels: 기능구현

#4 ✨ 유저 영속성 레이어 구현
  application/src/main/kotlin/com/threedays/application/user/port/inbound/CommandUser.kt
  application/src/main/kotlin/com/threedays/application/user/service/UserService.kt
  application/src/main/kotlin/com/threedays/application/user/vo/command/UserCommand.kt
  bootstrap/api/compose.yaml
  bootstrap/api/src/main/resources/application.yaml
  domain/src/main/kotlin/com/threedays/domain/user/entity/Location.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/User.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/UserProfile.kt
  domain/src/main/kotlin/com/threedays/domain/user/repository/LocationQueryRepository.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/LocationId.kt
  domain/src/test/kotlin/com/threedays/domain/user/entity/UserTest.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/adapter/UserPersistenceAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/LocationEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserDesiredPartnerEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserLocationEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserProfileEntity.kt
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/persistence/src/main/resources/db/migration/V1__init_user.sql
Labels: 기능구현

#5 [Enhance] Add location script sql
  bootstrap/api/compose.yaml
  gradle/libs.versions.toml
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/persistence/src/main/resources/db/scripts/add_locations.sql
Labels: 기타

#11 [Enhance] Add find all location api & test
  application/src/main/kotlin/com/threedays/application/user/port/inbound/QueryLocation.kt
  application/src/main/kotlin/com/threedays/application/user/service/LocationService.kt
  application/src/test/kotlin/com/threedays/application/user/service/LocationServiceTest.kt
  bootstrap/api/src/main/kotlin/com/threedays/bootstrap/api/location/LocationsController.kt
  domain/src/main/kotlin/com/threedays/domain/user/repository/LocationQueryRepository.kt
  domain/src/testFixtures/kotlin/com/threedays/domain/auth/repository/AbstractTestRepositorySpy.kt
  domain/src/testFixtures/kotlin/com/threedays/domain/auth/repository/LocationQueryRepositorySpy.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/adapter/LocationQueryPersistenceAdapter.kt
Labels: 기능구현

#12 👷 CI Workflow
  .github/workflows/cd-dev.yaml
  .github/workflows/ci.yaml
  bootstrap/api/build.gradle.kts
  gradle/libs.versions.toml
Labels: 기능구현

#14 🩹 트랜잭션 누락 추가
  application/src/main/kotlin/com/threedays/application/user/service/LocationService.kt
  bootstrap/api/src/main/kotlin/com/threedays/bootstrap/api/location/LocationsController.kt
Labels: 버그수정

#15 ✨ 회원 가입 토큰 개발
  domain/src/main/kotlin/com/threedays/domain/auth/entity/AuthToken.kt
  domain/src/main/kotlin/com/threedays/domain/auth/entity/RegisterToken.kt
  domain/src/main/kotlin/com/threedays/domain/auth/exception/AuthException.kt
  domain/src/test/kotlin/com/threedays/domain/auth/entity/RegisterTokenTest.kt
Labels: 기능구현

#17 ✨ 회사, 직장 도메인 추가
  application/src/main/kotlin/com/threedays/application/user/service/UserService.kt
  application/src/main/kotlin/com/threedays/application/user/vo/command/UserCommand.kt
  domain/src/main/kotlin/com/threedays/domain/auth/entity/RegisterToken.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/Company.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/Job.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/User.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/UserDesiredPartner.kt
  domain/src/main/kotlin/com/threedays/domain/user/entity/UserProfile.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/Company.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/CompanyId.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/Job.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/JobId.kt
  domain/src/main/kotlin/com/threedays/domain/user/vo/Location.kt
  domain/src/test/kotlin/com/threedays/domain/user/entity/UserTest.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/adapter/UserPersistenceAdapter.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/CompanyEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/JobEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserDesiredPartnerEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserDesiredPartnerJobOccupationEntity.kt
  infrastructure/persistence/src/main/kotlin/com/threedays/persistence/user/entity/UserProfileEntity.kt
  infrastructure/persistence/src/main/resources/application-persistence.yaml
  infrastructure/persistence/src/main/resources/db/migration/V1__init_user.sql
Labels: 기능구현
